# Generated by Django 6.0.3 on 2026-03-10 13:47

import cv_builder.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='is_temporary',
            field=models.BooleanField(default=False, help_text='True if CV was created from manual entry, not file upload'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='file',
            field=models.FileField(blank=True, help_text='CV file (PDF or DOCX)', null=True, upload_to=cv_builder.models.get_cv_upload_path),
        ),
        migrations.AlterField(
            model_name='cv',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
