# Generated by Django 6.0.3 on 2026-03-11 22:26

import cv_builder.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cv_builder", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CV",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title for this CV (e.g., 'Software Engineer CV')",
                        max_length=200,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="CV file (PDF or DOCX)",
                        null=True,
                        upload_to=cv_builder.models.get_cv_upload_path,
                    ),
                ),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                (
                    "is_temporary",
                    models.BooleanField(
                        default=False,
                        help_text="True if CV was created from manual entry, not file upload",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(help_text="File type: PDF or DOCX", max_length=10),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(help_text="File size in bytes"),
                ),
                (
                    "is_parsed",
                    models.BooleanField(default=False, help_text="Has CV been parsed?"),
                ),
                (
                    "is_analyzed",
                    models.BooleanField(
                        default=False, help_text="Has CV been analyzed?"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Soft delete flag"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cvs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "CV",
                "verbose_name_plural": "CVs",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="CVData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_text", models.TextField(help_text="Full text extracted from CV")),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                ("linkedin_url", models.URLField(blank=True, null=True)),
                ("github_url", models.URLField(blank=True, null=True)),
                ("website_url", models.URLField(blank=True, null=True)),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="Professional summary/objective",
                        null=True,
                    ),
                ),
                (
                    "skills",
                    models.JSONField(
                        default=list,
                        help_text="List of skills: ['Python', 'Django', 'React']",
                    ),
                ),
                (
                    "experience",
                    models.JSONField(
                        default=list,
                        help_text="List of experience objects with company, role, dates, etc.",
                    ),
                ),
                (
                    "education",
                    models.JSONField(
                        default=list,
                        help_text="List of education objects with institution, degree, dates, etc.",
                    ),
                ),
                (
                    "projects",
                    models.JSONField(
                        default=list,
                        help_text="List of project objects with name, description, tech stack, etc.",
                    ),
                ),
                (
                    "certifications",
                    models.JSONField(default=list, help_text="List of certifications"),
                ),
                (
                    "languages",
                    models.JSONField(
                        default=list, help_text="List of languages spoken"
                    ),
                ),
                (
                    "interests",
                    models.JSONField(
                        default=list, help_text="List of professional interests/hobbies"
                    ),
                ),
                (
                    "parsing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("parsing_error", models.TextField(blank=True, null=True)),
                ("extracted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cv",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data",
                        to="cv_builder.cv",
                    ),
                ),
            ],
            options={
                "verbose_name": "CV Data",
                "verbose_name_plural": "CV Data",
            },
        ),
        migrations.CreateModel(
            name="CVAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ats_score",
                    models.IntegerField(
                        default=0, help_text="ATS compatibility score (0-100)"
                    ),
                ),
                (
                    "overall_score",
                    models.IntegerField(
                        default=0, help_text="Overall CV quality score (0-100)"
                    ),
                ),
                (
                    "content_quality_score",
                    models.IntegerField(
                        default=0, help_text="Content quality score (0-100)"
                    ),
                ),
                (
                    "formatting_score",
                    models.IntegerField(
                        default=0, help_text="Formatting score (0-100)"
                    ),
                ),
                (
                    "strengths",
                    models.JSONField(default=list, help_text="List of CV strengths"),
                ),
                (
                    "weaknesses",
                    models.JSONField(
                        default=list, help_text="List of areas for improvement"
                    ),
                ),
                (
                    "suggestions",
                    models.JSONField(
                        default=list, help_text="AI-generated improvement suggestions"
                    ),
                ),
                (
                    "formatting_issues",
                    models.JSONField(
                        default=list, help_text="List of formatting issues found"
                    ),
                ),
                (
                    "missing_keywords",
                    models.JSONField(
                        default=list, help_text="Common keywords missing from CV"
                    ),
                ),
                (
                    "missing_sections",
                    models.JSONField(
                        default=list, help_text="Important sections missing from CV"
                    ),
                ),
                (
                    "detailed_checks",
                    models.JSONField(
                        default=dict,
                        help_text="Itemized check results grouped by category",
                    ),
                ),
                (
                    "analysis_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("analysis_error", models.TextField(blank=True, null=True)),
                ("analyzed_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cv_data",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="cv_builder.cvdata",
                    ),
                ),
            ],
            options={
                "verbose_name": "CV Analysis",
                "verbose_name_plural": "CV Analyses",
            },
        ),
        migrations.CreateModel(
            name="JobDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("company", models.CharField(max_length=200)),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                ("job_url", models.URLField(blank=True, null=True)),
                ("description", models.TextField(help_text="Full job description")),
                (
                    "requirements",
                    models.TextField(
                        blank=True, help_text="Job requirements section", null=True
                    ),
                ),
                (
                    "responsibilities",
                    models.TextField(
                        blank=True, help_text="Job responsibilities section", null=True
                    ),
                ),
                (
                    "qualifications",
                    models.TextField(
                        blank=True, help_text="Job qualifications section", null=True
                    ),
                ),
                (
                    "benefits",
                    models.TextField(
                        blank=True, help_text="Job benefits section", null=True
                    ),
                ),
                (
                    "keywords",
                    models.JSONField(
                        default=list,
                        help_text="Extracted keywords from job description",
                    ),
                ),
                (
                    "required_skills",
                    models.JSONField(
                        default=list, help_text="Required skills from job description"
                    ),
                ),
                (
                    "preferred_skills",
                    models.JSONField(
                        default=list, help_text="Preferred skills from job description"
                    ),
                ),
                ("is_parsed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_descriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Description",
                "verbose_name_plural": "Job Descriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CVVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                (
                    "title",
                    models.CharField(
                        help_text="Version title (e.g., 'Version 2 - Optimized for Google')",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of changes in this version"
                    ),
                ),
                (
                    "version_type",
                    models.CharField(
                        choices=[
                            ("original", "Original"),
                            ("ats_optimized", "ATS Optimized"),
                            ("job_tailored", "Job Tailored"),
                            ("custom", "Custom"),
                        ],
                        default="original",
                        max_length=20,
                    ),
                ),
                (
                    "optimization_target",
                    models.CharField(
                        blank=True,
                        help_text="Target job or company (e.g., 'Google SWE')",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "optimized_text",
                    models.TextField(help_text="Full text of optimized CV"),
                ),
                (
                    "keywords_added",
                    models.JSONField(
                        default=list, help_text="Keywords added in this version"
                    ),
                ),
                (
                    "changes_made",
                    models.JSONField(
                        default=list, help_text="List of changes made in this version"
                    ),
                ),
                (
                    "ats_score",
                    models.IntegerField(
                        blank=True, help_text="ATS score for this version", null=True
                    ),
                ),
                (
                    "overall_score",
                    models.IntegerField(
                        blank=True,
                        help_text="Overall score for this version",
                        null=True,
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=False, help_text="Is this the current active version?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="cv_builder.cv",
                    ),
                ),
            ],
            options={
                "verbose_name": "CV Version",
                "verbose_name_plural": "CV Versions",
                "ordering": ["-version_number"],
                "unique_together": {("cv", "version_number")},
            },
        ),
    ]
