# Generated by Django 6.0.3 on 2026-03-12 20:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.IntegerField()),
                ('order', models.IntegerField()),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('short_answer', 'Short Answer'), ('situational', 'Situational'), ('behavioural', 'Behavioural'), ('technical', 'Technical')], max_length=20)),
                ('question_text', models.TextField()),
                ('options', models.JSONField(blank=True, null=True)),
                ('correct_answer', models.TextField(blank=True, null=True)),
                ('ideal_answer_guide', models.TextField(blank=True, null=True)),
                ('section', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['phase', 'order'],
            },
        ),
        migrations.CreateModel(
            name='InterviewAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('score', models.FloatField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('needs_review', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='interview_system.interviewquestion')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('career_goal', models.TextField()),
                ('experience_level', models.CharField(choices=[('junior', 'Junior / Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior Level'), ('manager', 'Managerial / Team Lead'), ('director', 'Director / Executive')], max_length=20)),
                ('interview_type', models.CharField(choices=[('hr', 'HR / Behavioural'), ('technical', 'Technical'), ('mixed', 'Mixed')], max_length=20)),
                ('mode', models.CharField(default='text', max_length=10)),
                ('status', models.CharField(choices=[('phase1_test', 'Phase 1 - Written Test'), ('phase1_review', 'Phase 1 - Review'), ('phase2_interview', 'Phase 2 - Interview'), ('phase2_review', 'Phase 2 - Review'), ('phase3_interview', 'Phase 3 - Deep Dive'), ('phase3_review', 'Phase 3 - Review'), ('complete', 'Complete')], default='phase1_test', max_length=30)),
                ('phase1_score', models.FloatField(blank=True, null=True)),
                ('phase2_score', models.FloatField(blank=True, null=True)),
                ('phase3_score', models.FloatField(blank=True, null=True)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('phase1_passed', models.BooleanField(blank=True, null=True)),
                ('phase2_passed', models.BooleanField(blank=True, null=True)),
                ('phase3_passed', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interview_system.interviewsession'),
        ),
        migrations.CreateModel(
            name='ReviewMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.IntegerField()),
                ('role', models.CharField(max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interview_system.interviewquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_messages', to='interview_system.interviewsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
