# Generated by Django 6.0.3 on 2026-03-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewquestion',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('short_answer', 'Short Answer'), ('situational', 'Situational'), ('behavioural', 'Behavioural'), ('technical', 'Technical')], max_length=50),
        ),
    ]
