# Generated by Django 6.0.3 on 2026-03-12 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_system', '0002_alter_interviewquestion_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewsession',
            name='status',
            field=models.CharField(choices=[('intro', 'Introduction'), ('phase1_test', 'Phase 1 - Written Test'), ('phase1_review', 'Phase 1 - Review'), ('phase2_interview', 'Phase 2 - Interview'), ('phase2_review', 'Phase 2 - Review'), ('phase3_interview', 'Phase 3 - Deep Dive'), ('phase3_review', 'Phase 3 - Review'), ('complete', 'Complete')], default='intro', max_length=30),
        ),
    ]
