# Generated by Django 6.0.3 on 2026-03-07 12:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cv_builder', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('linkedin', 'LinkedIn'), ('indeed', 'Indeed'), ('glassdoor', 'Glassdoor'), ('adzuna', 'Adzuna'), ('remotive', 'Remotive'), ('scraped', 'Web Scraped')], default='manual', max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('job_url', models.URLField(blank=True, max_length=500, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_currency', models.CharField(blank=True, default='USD', max_length=10)),
                ('job_type', models.CharField(blank=True, choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship'), ('freelance', 'Freelance'), ('remote', 'Remote')], max_length=20, null=True)),
                ('experience_level', models.CharField(blank=True, choices=[('entry', 'Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior Level'), ('lead', 'Lead/Manager'), ('executive', 'Executive')], max_length=20, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('qualifications', models.TextField(blank=True, null=True)),
                ('benefits', models.TextField(blank=True, null=True)),
                ('skills_required', models.JSONField(blank=True, default=list)),
                ('skills_optional', models.JSONField(blank=True, default=list)),
                ('responsibilities', models.JSONField(blank=True, default=list)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('company_logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('posted_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('application_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['title'], name='job_system__title_eaab74_idx'), models.Index(fields=['company'], name='job_system__company_551600_idx'), models.Index(fields=['location'], name='job_system__locatio_5d0d96_idx'), models.Index(fields=['job_type'], name='job_system__job_typ_782cf3_idx'), models.Index(fields=['experience_level'], name='job_system__experie_5f774d_idx'), models.Index(fields=['is_active'], name='job_system__is_acti_03c856_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('job_type', models.CharField(blank=True, max_length=20, null=True)),
                ('experience_level', models.CharField(blank=True, max_length=20, null=True)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('applied', 'Applied'), ('under_review', 'Under Review'), ('screening', 'Phone Screening'), ('interview', 'Interview'), ('technical', 'Technical Interview'), ('offer', 'Offer Received'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('hired', 'Hired')], default='draft', max_length=20)),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('application_date', models.DateField(blank=True, null=True)),
                ('application_url', models.URLField(blank=True, max_length=500, null=True)),
                ('interview_date', models.DateTimeField(blank=True, null=True)),
                ('interview_type', models.CharField(blank=True, max_length=50, null=True)),
                ('interview_notes', models.TextField(blank=True, null=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('follow_up_completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('reminders', models.JSONField(blank=True, default=list)),
                ('match_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('matched_skills', models.JSONField(blank=True, default=list)),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cv_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='cv_builder.cvversion')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='job_system.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='job_system__user_id_57baf7_idx'), models.Index(fields=['application_date'], name='job_system__applica_d6d014_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_match', models.DecimalField(decimal_places=2, max_digits=5)),
                ('skill_match', models.DecimalField(decimal_places=2, max_digits=5)),
                ('experience_match', models.DecimalField(decimal_places=2, max_digits=5)),
                ('location_match', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('matched_skills', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('additional_skills', models.JSONField(blank=True, default=list)),
                ('suggestions', models.JSONField(default=list)),
                ('improvement_ideas', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cv_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_matches', to='cv_builder.cvversion')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='job_system.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-overall_match'],
                'indexes': [models.Index(fields=['user', 'overall_match'], name='job_system__user_id_7f0d2d_idx'), models.Index(fields=['overall_match'], name='job_system__overall_e741ab_idx')],
                'unique_together': {('user', 'job', 'cv_version')},
            },
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='job_system.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'job')},
            },
        ),
    ]
