# Generated by Django 6.0.3 on 2026-03-07 14:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_builder', '0002_schema_with_uuid'),
        ('job_system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Job Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='mode',
            field=models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto-Apply')], default='manual', max_length=20),
        ),
        migrations.CreateModel(
            name='AutoApplicationBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('applying', 'Applying'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('search_query', models.CharField(blank=True, max_length=200, null=True)),
                ('search_location', models.CharField(blank=True, max_length=200, null=True)),
                ('search_filters', models.JSONField(blank=True, default=dict)),
                ('total_jobs', models.PositiveIntegerField(default=0)),
                ('approved_jobs', models.PositiveIntegerField(default=0)),
                ('rejected_jobs', models.PositiveIntegerField(default=0)),
                ('successful_applications', models.PositiveIntegerField(default=0)),
                ('failed_applications', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cv_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_application_batches', to='cv_builder.cvversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_application_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auto-Application Batch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutoApplicationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_approval_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('applying', 'Applying'), ('applied', 'Applied'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('application_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('applying', 'Applying'), ('applied', 'Applied'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('match_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('matched_skills', models.JSONField(blank=True, default=list)),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('custom_cv', models.JSONField(blank=True, null=True)),
                ('custom_cover_letter', models.TextField(blank=True, null=True)),
                ('edited_cv', models.JSONField(blank=True, null=True)),
                ('edited_cover_letter', models.TextField(blank=True, null=True)),
                ('application_url', models.URLField(blank=True, max_length=500, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='job_system.autoapplicationbatch')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_application_items', to='job_system.job')),
                ('job_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_application_item', to='job_system.jobapplication')),
            ],
            options={
                'verbose_name': 'Auto-Application Item',
                'ordering': ['-match_score'],
            },
        ),
        migrations.CreateModel(
            name='JobCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('search_key', models.CharField(max_length=500, unique=True)),
                ('search_params', models.JSONField()),
                ('results', models.JSONField()),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['search_key'], name='job_system__search__789cd9_idx'), models.Index(fields=['expires_at'], name='job_system__expires_7e3e12_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserApplicationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approval_mode', models.CharField(choices=[('always', 'Always Require Approval'), ('after_trust', 'After Trust (Require X approvals first)'), ('never', 'Never Require Approval')], default='always', max_length=20)),
                ('approvals_required_for_trust', models.PositiveIntegerField(default=10)),
                ('min_match_score', models.DecimalField(decimal_places=2, default=70.0, max_digits=5)),
                ('preferred_job_types', models.JSONField(blank=True, default=list)),
                ('preferred_locations', models.JSONField(blank=True, default=list)),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('blacklisted_companies', models.JSONField(blank=True, default=list)),
                ('apply_immediately', models.BooleanField(default=True)),
                ('apply_rate_limit', models.PositiveIntegerField(default=10)),
                ('apply_start_time', models.TimeField(blank=True, null=True)),
                ('apply_end_time', models.TimeField(blank=True, null=True)),
                ('trust_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_approvals', models.PositiveIntegerField(default=0)),
                ('total_rejections', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auto_apply_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Auto-Apply Preferences',
            },
        ),
        migrations.AddIndex(
            model_name='autoapplicationbatch',
            index=models.Index(fields=['user', 'status'], name='job_system__user_id_c60258_idx'),
        ),
        migrations.AddIndex(
            model_name='autoapplicationbatch',
            index=models.Index(fields=['created_at'], name='job_system__created_aeef41_idx'),
        ),
        migrations.AddIndex(
            model_name='autoapplicationitem',
            index=models.Index(fields=['batch', 'user_approval_status'], name='job_system__batch_i_60ff3b_idx'),
        ),
        migrations.AddIndex(
            model_name='autoapplicationitem',
            index=models.Index(fields=['match_score'], name='job_system__match_s_dbccc0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='autoapplicationitem',
            unique_together={('batch', 'job')},
        ),
    ]
