# Generated by Django 6.0.3 on 2026-03-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_system', '0002_jobcategory_jobapplication_mode_autoapplicationbatch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('entry', 'Entry Level'), ('entry_level', 'Entry Level'), ('mid', 'Mid Level'), ('mid_level', 'Mid Level'), ('senior', 'Senior Level'), ('senior_level', 'Senior Level'), ('lead', 'Lead/Manager'), ('executive', 'Executive')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='external_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('linkedin', 'LinkedIn'), ('indeed', 'Indeed'), ('glassdoor', 'Glassdoor'), ('ziprecruiter', 'ZipRecruiter'), ('adzuna', 'Adzuna'), ('remotive', 'Remotive'), ('arbeitnow', 'Arbeitnow'), ('jobicy', 'Jobicy'), ('remoteok', 'RemoteOK'), ('themuse', 'The Muse'), ('brightermonday', 'BrighterMonday'), ('fuzu', 'Fuzu'), ('kenyajob', 'KenyaJob'), ('myjobmag', 'MyJobMag'), ('scraped', 'Web Scraped')], default='manual', max_length=20),
        ),
    ]
