# Generated by Django 6.0.3 on 2026-03-12 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_system', '0005_add_kenyan_source_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('linkedin', 'LinkedIn'), ('indeed', 'Indeed'), ('glassdoor', 'Glassdoor'), ('ziprecruiter', 'ZipRecruiter'), ('adzuna', 'Adzuna'), ('remotive', 'Remotive'), ('arbeitnow', 'Arbeitnow'), ('jobicy', 'Jobicy'), ('remoteok', 'RemoteOK'), ('themuse', 'The Muse'), ('brightermonday', 'BrighterMonday'), ('fuzu', 'Fuzu'), ('kenyajob', 'KenyaJob'), ('myjobmag', 'MyJobMag'), ('jobwebkenya', 'Jobwebkenya'), ('ngojobs', 'NGO Jobs Africa'), ('corporatestaffing', 'Corporate Staffing KE'), ('nationkenya', 'Nation Kenya'), ('jobberman', 'Jobberman (Nigeria)'), ('career24', 'Career24 (South Africa)'), ('indeedrss', 'Indeed RSS'), ('weworkremotely', 'We Work Remotely'), ('scraped', 'Web Scraped')], default='manual', max_length=20),
        ),
    ]
