# Generated by Django 6.0.3 on 2026-03-10 22:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIFeatureCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("cv_write", "Write CV from scratch"),
                            ("cv_revamp", "Revamp existing CV"),
                            ("cv_customize", "Customize CV for job"),
                            ("cover_letter", "Write cover letter"),
                            ("career_guidance", "Career guidance (per message)"),
                            ("job_match", "Job matching"),
                            ("interview_question", "Interview question (future)"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "credits_cost",
                    models.PositiveIntegerField(help_text="Credits deducted per use"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI Feature Cost",
                "verbose_name_plural": "AI Feature Costs",
            },
        ),
        migrations.CreateModel(
            name="TokenPack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Starter, Standard, Pro", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="What users get with this pack"
                    ),
                ),
                (
                    "credits",
                    models.PositiveIntegerField(
                        help_text="Number of credits in this pack"
                    ),
                ),
                (
                    "price_kes",
                    models.DecimalField(
                        decimal_places=2, help_text="Price in KES", max_digits=10
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Show this pack to users"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Highlight as most popular"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Token Pack",
                "verbose_name_plural": "Token Packs",
                "ordering": ["sort_order", "price_kes"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("mpesa", "M-Pesa"),
                            ("card", "Visa/Mastercard (Flutterwave)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount_kes", models.DecimalField(decimal_places=2, max_digits=10)),
                ("credits_to_add", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("mpesa_phone", models.CharField(blank=True, max_length=20)),
                (
                    "mpesa_checkout_request_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "mpesa_merchant_request_id",
                    models.CharField(blank=True, max_length=100),
                ),
                ("mpesa_receipt_number", models.CharField(blank=True, max_length=50)),
                (
                    "flutterwave_tx_ref",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("flutterwave_tx_id", models.CharField(blank=True, max_length=100)),
                ("gateway_response", models.JSONField(blank=True, default=dict)),
                ("credits_added", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "token_pack",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payments.tokenpack",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TokenTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Purchase"),
                            ("usage", "AI Feature Usage"),
                            ("bonus", "Bonus / Admin Gift"),
                            ("refund", "Refund"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "credits",
                    models.IntegerField(
                        help_text="Positive = added, Negative = deducted"
                    ),
                ),
                ("balance_after", models.PositiveIntegerField()),
                ("description", models.CharField(max_length=255)),
                ("feature", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="payments.payment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Token Transaction",
                "verbose_name_plural": "Token Transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserTokenBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance", models.PositiveIntegerField(default=0)),
                ("total_purchased", models.PositiveIntegerField(default=0)),
                ("total_used", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token_balance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Token Balance",
                "verbose_name_plural": "User Token Balances",
            },
        ),
    ]
