# Generated by Django 6.0.3 on 2026-03-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="flutterwave_tx_id",
            new_name="pesapal_order_ref",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="flutterwave_tx_ref",
            new_name="pesapal_order_tracking_id",
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("mpesa", "M-Pesa"), ("card", "Visa/Mastercard (PesaPal)")],
                max_length=20,
            ),
        ),
    ]
